name: Deploy Lambda: Fulcrum Process

on:
  push:
    paths:
      - 'lambdas/fulcrum_process/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Package Lambda
        run: |
          cd lambdas/fulcrum_process
          zip -r ../fulcrum_process.zip .

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \\
            --function-name fulcrum_process \\
            --zip-file fileb://lambdas/fulcrum_process.zip